depromeet/ygtang-server

.github/workflows/gradle.yml
.gitignore
build.gradle
module-api/build.gradle
module-domain/build.gradle
module-web/src/main/java/inspiration/v1/member/MemberController.java
module-web/src/main/resources/application-local.yml
module-web/src/main/resources/application.yml

- Resolve: #1 
- 애자일의 효율성을 위해 git action CI 적용
- 환경 별 profile 분리(현재는 local만 분리) 및 설정 값 .env file로 관리
- data-jpa dependency가 추가되어 있는데, 이로 인해 database 관련 설정을 아직 하지 않아서 빌드를 할 수 없으므로 잠시 삭제했습니다!
- keybase에서 env file 올려놨어요!
1. Enable EnvFIle check 후,
2. "+" 클릭해서 key base에 있는 env file을 자신의 로컬에 저장
3. env file 설정 값(port 등)을 자신의 로컬 환경에 맞게 수정하시고
4. 빌드 하시면 됩니다.
- [✅ ] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [✅] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?

환경 별 profile 분리 및 애자일의 효율성을 위해 git action CI 적용

---

README.md
module-common/src/main/java/inspiration/enumeration/ExceptionType.java
module-common/src/main/java/inspiration/exception/PostNotFoundException.java
module-web/build.gradle
module-web/src/main/java/inspiration/v1/advice/ErrorResponse.java
module-web/src/main/java/inspiration/v1/advice/GlobalExceptionController.java
module-web/src/main/resources/application-local.yml

- Resolve: #4
- exception handler 관련 구조 설계
- comment 환영입니다.
-

exception handler 관련 디렉토리 구조 설계

---

module-common/src/main/java/inspiration/config/security/SecurityConfiguration.java

- #18
- failed to fetch solution
-
-

feat : failed to fetch solution

---

module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
module-web/src/main/java/inspiration/v1/member/MemberController.java

- #23 
- 이메일 인증 상태를 확인하고 상태를 반환하는 api 추가
-
-

feat: 이메일 인증 상태를 확인하고 상태를 반환하는 api 추가

---

module-api/src/main/java/inspiration/auth/AuthService.java
module-common/src/main/java/inspiration/config/security/JwtProvider.java
module-web/src/main/java/inspiration/v1/reissue/ReissueController.java

- #39 
- 리프레시 토큰 페이로드에 member_id 삽입 
- @AuthenticationPrincipal 제거 후 리프레시 토큰 페이로드에서 member_id 조회
-
-

Ressiue Api Refactor

---

module-api/src/main/java/inspiration/auth/AuthService.java
module-api/src/main/java/inspiration/member/response/MemberInfoResponse.java
module-web/src/main/java/inspiration/v1/member/MemberController.java

1. 사용자 정보 조회
Feat #43
- 
- 
-
-

Feat: getMyInfo

---

module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
module-api/src/main/java/inspiration/emailauth/ResetPasswordEmailSendService.java
module-api/src/main/java/inspiration/emailauth/ResetPasswordForAuthSendService.java
module-api/src/main/java/inspiration/member/MemberService.java
module-common/src/main/java/inspiration/config/security/SecurityConfiguration.java
module-common/src/main/java/inspiration/enumeration/ExpireTimeConstants.java
module-common/src/main/java/inspiration/enumeration/RedisKey.java
module-common/src/main/java/inspiration/property/MailProperties.java
module-common/src/main/java/inspiration/utils/GetResetPasswordUtil.java
module-domain/src/main/java/inspiration/passwordauth/PasswordAuth.java
module-domain/src/main/java/inspiration/passwordauth/PasswordAuthRepository.java
module-web/src/main/java/inspiration/v1/auth/AuthController.java
module-web/src/main/java/inspiration/v1/member/MemberController.java
module-web/src/main/resources/application-dev.yml
module-web/src/main/resources/application-local.yml
module-web/src/main/resources/db/migration/V12__create_password_auth_table.sql

- #42 
- 비밀번호 초기화를 위해 메일 전송 api
- 비밀번호 초기화를 위해 메일 전송 후 인증 api 추가
- 비밀번호 초기화 api 추가
- 비밀번호 변경 api 수정
-
-

비밀번호 초기화 api 추가, 비밀번호 변경 api 수정

---

module-api/src/main/java/inspiration/member/MemberService.java
module-api/src/main/java/inspiration/member/request/UpdateNicknameRequest.java
module-domain/src/main/java/inspiration/member/Member.java
module-web/src/main/java/inspiration/v1/member/MemberController.java

- #47 
- 
- 닉네임 변경 api 추가되었습니다.
-

닉네임 변경 api 구현

---

module-api/src/main/java/inspiration/inspiration/InspirationService.java
module-api/src/main/java/inspiration/inspiration_tag/InspirationTagService.java
module-api/src/main/java/inspiration/member/MemberService.java
module-api/src/main/java/inspiration/tag/TagService.java
module-domain/src/main/java/inspiration/emailauth/EmailAuthRepository.java
module-domain/src/main/java/inspiration/inspiration/Inspiration.java
module-domain/src/main/java/inspiration/inspiration/InspirationRepository.java
module-domain/src/main/java/inspiration/inspiration_tag/InspirationTagRepository.java
module-domain/src/main/java/inspiration/tag/TagRepository.java
module-web/src/main/java/inspiration/v1/inspiration/InspirationController.java
module-web/src/main/java/inspiration/v1/member/MemberController.java
module-web/src/main/java/inspiration/v1/tag/TagController.java
module-web/src/main/resources/db/migration/V13__alter_inspiration_drop_is_deleted.sql

Feat #52
- #52 
- inspiration 테이블 is_deleted, del_date_time column 삭제
- 영감 삭제 메소드 수정
- 영감 삭제 시 해당 영감 태깅 해제 로직 추가
- 전체 영감 삭제
- 전체 태그 삭제
- 계정 삭제(전체 영감 삭제, 전체 태그 삭제 로직 포함)
-
-

Feat: RemoveAllInspiration, RemoveUser

---

module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
module-common/src/main/java/inspiration/utils/PasswordAuthRedirectViewUtil.java

비밀번호 초기화 링크 클릭시 app view로 redirect

---

module-api/src/main/java/inspiration/inspiration/InspirationService.java
module-api/src/main/java/inspiration/inspiration_tag/InspirationTagService.java
module-domain/src/main/java/inspiration/inspiration_tag/InspirationTagRepository.java
module-web/src/main/java/inspiration/v1/tag/TagController.java

- #59 
- 영감에 태깅되어 있는 태그 삭제요청 시, 해당되는 태깅들 모두 해제한 후 삭제하도록 수정하였습니다.
-
-

Update: removeTag

---

module-domain/src/main/java/inspiration/member/MemberRepository.java

fix : member id 조회 동시성 제어

---

module-domain/src/main/java/inspiration/inspiration/InspirationRepository.java
module-domain/src/main/java/inspiration/member/MemberRepository.java
module-domain/src/main/java/inspiration/tag/TagRepository.java

동시성 제어 write -> read

---

module-domain/src/main/java/inspiration/inspiration/InspirationRepository.java
module-domain/src/main/java/inspiration/tag/TagRepository.java
module-web/src/main/java/inspiration/DeployController.java

영감 태깅 동시성 제어 - 비관적락 WRITE 적용

---

module-api/src/main/java/inspiration/emailauth/EmailAuthService.java
module-api/src/main/java/inspiration/emailauth/ResetPasswordEmailSendService.java
module-api/src/main/java/inspiration/emailauth/SignUpEmailSendService.java
module-api/src/main/java/inspiration/inspiration/InspirationService.java
module-api/src/main/java/inspiration/inspiration_tag/InspirationTagService.java
module-api/src/main/java/inspiration/tag/TagService.java
module-domain/src/main/java/inspiration/emailauth/EmailAuthRepository.java
module-domain/src/main/java/inspiration/inspiration/InspirationRepository.java
module-domain/src/main/java/inspiration/inspiration_tag/InspirationTagRepository.java
module-domain/src/main/java/inspiration/member/MemberRepository.java
module-domain/src/main/java/inspiration/tag/TagRepository.java

- #64 
- 태그 등록 시 중복 확인
- 사용하지 않는 코드 제거
-
-

feat: 태그 등록시 중복 확인

---

module-api/build.gradle
module-api/src/main/java/inspiration/inspiration/InspirationService.java
module-web/src/main/resources/application-dev.yml

- #66 
- Datasource URL: useUnicode 속성 추가
- 링크 적합성 판단 시, OG 데이터가 없을 경우, html header 메타태그로 반환
- 링크 적합성 판단 시, 최초 HttpURLConnection 을 통해 유효성 확인
-
-

fix: 링크 적합성 판단 로직 개선

---

module-api/src/main/java/inspiration/signup/SignupService.java
module-common/src/main/java/inspiration/config/security/JwtProvider.java
module-common/src/main/java/inspiration/config/security/TokenResponse.java
module-web/src/main/java/inspiration/v1/signup/SignUpController.java

- #74 
- 회원가입시 토큰 발급
- 회원가입 후 다시 로그인을 진행하여 서비스를 이용할때, 믹스패널에서 이탈율이 높게 나타나는 지표가 확인되어 회원가입시에도 토큰 발급
-
-

refactor : 회원가입시에도 토큰 발급

---

module-api/src/main/java/inspiration/inspiration/InspirationService.java
module-api/src/main/java/inspiration/tag/TagService.java

- #76 
- 캐싱 처리 시, 결합 key 변경
-
-

refactor: 캐싱 처리 시, 결합 key 변경

---

module-api/src/main/java/inspiration/inspiration/InspirationService.java
module-domain/src/main/java/inspiration/inspiration/InspirationRepository.java
module-domain/src/main/java/inspiration/inspiration_tag/InspirationTagRepository.java
module-domain/src/main/java/inspiration/tag/TagRepository.java

- #79
-  회원정보 초기화 시에 등록태그 모두 제거
- bulk delete query 적용
-
-

feat: 회원정보 초기화 시에 등록태그 모두 제거(bulk delete 적용)

---

module-api/src/main/java/inspiration/auth/AuthService.java
module-api/src/main/java/inspiration/redis/RedisService.java

토큰 관련 리팩토링

---

build.gradle
module-web/src/main/java/inspiration/v1/advice/GlobalExceptionController.java
module-web/src/main/resources/application-dev.yml
module-web/src/main/resources/application-local.yml
module-web/src/main/resources/logback-spring.xml

 에러 로깅 슬랙 연동

---

module-api/src/main/java/inspiration/emailauth/SignUpEmailSendService.java
module-common/src/main/java/inspiration/jobs/WebConfig.java
module-common/src/main/java/inspiration/utils/PolicyRedirectViewUtil.java

fix : 이메일 인증시 리다이렉트 링크 및 이메일 인증 html 수정

---

.github/CODEOWNERS

- resolve #101 
- CODEOWNERS 파일 추가 
-
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

chore: CODEOWNERS 파일 추가

---

module-web/src/main/resources/logback-spring.xml

fix: 오타 수정

---

build.gradle
gradle.properties
module-api/build.gradle
module-web/src/test/java/inspiration/ApplicationTests.java
module-web/src/test/java/inspiration/TestRedisConfiguration.java
module-web/src/test/resources/application.yml

- resolve #107 
- `@SpringBootTest` 사용하기 위해 embedded db, redis 등 추가
- 운영 및 테스트 환경에서 사용하지 않는 의존성 제거 (aws java sdk ec2, ..)
- test context 에서 사용하는 application.yml 추가
- 
-
-

test: 테스트 위한 환경 설정

---

module-batch/src/main/java/inspiration/application/member/MemberInfoConfig.java
module-domain/build.gradle
module-domain/src/main/java/inspiration/domain/member/MemberRepository.java
module-domain/src/main/java/inspiration/domain/member/MemberRepositoryCustom.java
module-domain/src/main/java/inspiration/domain/member/MemberRepositoryImpl.java

- #112 
- querydsl 의존성 추가
- 사용 예제 추가 (id 로 회원 조회)
-
<!--

feat: querydsl 추가

---

.github/workflows/dev_deploy.yml
.github/workflows/prod_deploy.yml
.gitignore
docker-compose.yml
dockerfile
module-web/src/main/java/inspiration/YgtangWebApplication.java
scripts/run_new_was.sh

- #120 
- git actions, s3, code deploy, docker를 이용한 배포 자동화 환경 구축
- 추후 docker image를 생성하여 ECR로 업로드하여 배포하는 방향으로 개선 예정
- ECR -> EC2 간에 연동 레퍼런스를 좀 더 찾아볼 필요가 있음
-

feat: 배포 자동화 환경 구축

---

build.gradle
docker-compose.yml
scripts/health_check.sh
scripts/run_new_was.sh

- #120 
- docker 설정 변경
- health check script 추가 
-
-

feat: docker 설정 변경, health check 추가

---

module-api/src/main/java/inspiration/domain/emailauth/EmailAuthService.java
module-api/src/main/java/inspiration/domain/emailauth/request/AuthenticateEmailRequest.java
module-api/src/main/java/inspiration/domain/emailauth/request/SendEmailRequest.java
module-api/src/main/java/inspiration/domain/member/request/SignUpRequest.java
module-web/src/main/java/inspiration/v1/auth/AuthController.java
module-web/src/main/java/inspiration/v1/signup/SignUpController.java
module-web/src/test/java/inspiration/DeployControllerTest.java
module-web/src/test/java/inspiration/v1/auth/AuthControllerTest.java
module-web/src/test/java/inspiration/v1/signup/SignUpControllerTest.java

- resolve #122
- 테스트케이스 추가
- 차례로 api 호출해야하는 경우 중복코드가 생기게 되는데, helper 등을 추가해서 해결할 수 있을거같습니다.

test: 인증, 가입 테스트 추가

---

docker-compose.yml

- #120 
- docker-compose env 추가
-
-

feat: docker compose env 추가

---

module-api/src/main/java/inspiration/domain/inspiration/InspirationService.java
module-domain/src/main/java/inspiration/domain/inspiration/InspirationRepositoryImpl.java
module-web/src/main/java/inspiration/v1/inspiration/InspirationController.java

- #97 
- service, controller 반영했습니다.
- 
-

Feat: 영감 필터링

---

module-batch/Dockerfile
module-web/Dockerfile
module-web/build.gradle

config: Add docker file

---

module-api/src/main/java/inspiration/domain/inspiration/InspirationService.java
module-domain/src/main/java/inspiration/domain/inspiration/Inspiration.java

- resolve #126
- 영감 한개, 여러개 삭제시 연결된 파일도 삭제

fix: 영감 삭제시 연결된 파일도 삭제

---

gradle.properties
module-api/build.gradle
module-api/src/main/java/inspiration/aws/AwsS3Config.java
module-api/src/main/java/inspiration/aws/AwsS3Service.java

- resolve #134
- spring cloud starter aws 의존성 제거하고, aws-java-sdk-s3 만 사용함
- spring cloud aws 의 기능을 활용하고있지않고, 애플리케이션을 특정 벤더에 종속적으로 개발하는 것도 좋지 않아보여서 변경했습니다.

config: aws-java-sdk-s3 만 사용하도록 변경

---

module-domain/src/main/java/inspiration/infrastructure/mail/MailSenderConfig.java

fix: 메일발송 실패하는 현상 해결

---

.github/workflows/gradle.yml

- resolve #142 
- develop 브랜치로 PR 올린 상태에서 feature 브랜치 푸시할 때, 중복으로 빌드하지 않도록 변경
-
-

config: GitHub Action 빌드 조건 수정

---

module-api/src/main/java/inspiration/auth/AuthService.java
module-api/src/main/java/inspiration/auth/jwt/JwtProvider.java

- resolve #106 
- 로그인시 이미 만료된 accessToken 을 응답하는 경우 있음
- accessToken, refreshToken 이 만료되었으면 새로 만들어서 응답
-
-

fix: 로그인시 유효한 accessToken 만 응답

---

module-web/src/main/java/inspiration/infrastructure/SecurityConfiguration.java

refactor: 불필요한 로그 제거

---

build.gradle
gradle.properties
module-api/src/main/java/inspiration/domain/emailauth/ResetPasswordForAuthSendService.java
module-api/src/main/java/inspiration/domain/emailauth/SignUpEmailSendService.java
module-domain/src/main/java/inspiration/infrastructure/jaspyt/JasyptConfig.java
module-domain/src/main/resources/application-dev.yml
module-domain/src/main/resources/application-local.yml
module-domain/src/main/resources/application-prod.yml
module-domain/src/main/resources/application.yml
module-domain/src/test/java/inspiration/InspirationApplicationTests.java
module-domain/src/test/java/inspiration/TestDomainApplication.java
module-domain/src/test/java/inspiration/TestRedisConfiguration.java
module-domain/src/test/java/inspiration/infrastructure/jaspyt/JasyptConfigTest.java
module-domain/src/test/resources/application.yml
module-web/src/main/resources/web-dev.yml
module-web/src/main/resources/web-local.yml
module-web/src/main/resources/web-prod.yml
module-web/src/main/resources/web.yml

refactor: 주입받는 변수 관리 방식 변경

---

module-batch/src/main/java/inspiration/application/tag/TagRankingConfig.java
module-batch/src/main/resources/batch-dev.yml
module-batch/src/main/resources/batch-local.yml
module-batch/src/main/resources/batch-prod.yml
module-batch/src/main/resources/batch.yml

config: 암호화된 설정 추가

---

.gitignore
module-domain/src/main/resources/application-dev.yml
module-domain/src/main/resources/application-prod.yml
module-domain/src/main/resources/application.yml
module-web/src/main/java/inspiration/infrastructure/SecurityConfiguration.java
module-web/src/main/resources/logback-spring.xml
module-web/src/main/resources/web.yml

- resolve #150
- local 에서 console appender 사용
- dev, prod 에서 slack, file appender 사용
-
-

config: 환경별로 로깅 설정 변경

---

build.gradle
module-domain/src/main/java/inspiration/infrastructure/redis/EmbeddedRedisConfiguration.java
module-domain/src/main/resources/application-local.yml
module-domain/src/test/java/inspiration/TestDomainApplication.java
module-web/src/test/java/inspiration/v1/auth/AuthControllerTest.java

- resolve #152
- elasticache 외부접속시키려면 까다로워서, local 환경에서는 embedded redis 를 사용합니다
-
-

config: local profile 이면 embedded redis 사용하도록 변경

---

module-web/src/main/resources/web.yml

config: 불필요한 로그 제외

---

module-api/src/main/java/inspiration/domain/inspiration/InspirationService.java
module-api/src/main/java/inspiration/domain/inspiration/opengraph/YgtangOgMetaElementHtmlParser.java
module-domain/src/main/java/inspiration/infrastructure/spring/ExecutorConfig.java

- resolve #161 
opengraph metadata 조회하기 위해 url 호출, 파싱 로직 처리시
- 요청받은 thread 1개로 직렬로 처리
- ThreadPoolTaskExecutor 사용해서 병렬로 처리
-
-

feat: opengraph 여러개 조회시 병렬 처리

---

.github/workflows/dev_deploy.yml
appspec.yml
docker-compose.yml
scripts/deploy.sh
scripts/login_ecr.sh

- #120 
- GitAction - CodeBuild 연동
- S3- Code Deploy를 통한 배포파일 로드
- Code Deploy를 통한 Docker Container 구동
- 개발 버전 구동 확인 후, 운영환경 반영 예정
-

feat: docker build를 위한 AWS CodeBuild 환경 연동

---

.github/workflows/dev_deploy.yml
appspec.yml
docker-compose.yml
module-web/src/main/java/inspiration/infrastructure/WebConfig.java
scripts/deploy.sh
scripts/login_ecr.sh

- #120 
- 빌드 자동화를 위한 @SuppressWarning 추가
-
-

빌드 자동화를 위한 @SuppressWarning 추가

---

module-api/src/main/java/inspiration/domain/inspiration/InspirationService.java
module-api/src/main/java/inspiration/domain/tag/TagService.java

config: 캐시 제거

---

README.md

docs: readme owner에 해성님 추가

---

module-web/src/main/resources/logback-spring.xml

chore: local 에서 불필요한 로그 파일 생기는 현상 해결

---

module-api/src/main/java/inspiration/domain/inspiration/InspirationService.java
module-domain/src/main/java/inspiration/domain/inspiration/InspirationRepositoryCustom.java
module-domain/src/main/java/inspiration/domain/inspiration/InspirationRepositoryImpl.java
module-web/src/main/java/inspiration/v1/inspiration/InspirationController.java

- Add: #180
- 입력 단위 LocalDateTime에서 LocalDate로 변경
- 비교범위 이상-이하로 변경
- redis 관련 이슈 때문에 EmbeddedRedisConfiguration에 어노테이션 두개 지운 상태로 개발했습니다. 커밋은 다시 살려놓은 상태로 올렸습니다.
- 이슈넘버 180인데 브랜치에 108로 잘못 적었네요…ㅜㅜ
-

add: Filtering

---

module-web/build.gradle

- releated #103
- 배포된(동작중인) 코드 버전 확인을 위해 git properties 플러그인 다시 추가
-
-

feat: actuator info endpoint 로 코드 버전 정보 출력

---

module-web/build.gradle
module-web/src/main/java/inspiration/infrastructure/SecurityConfiguration.java
module-web/src/main/resources/web-local.yml
module-web/src/main/resources/web.yml

- resolve #186 
- prometheus 의존성,설정 추가
-
- https://micrometer.io/docs/registry/prometheus
- https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.export.prometheus

feat: prometheus metric 추가

---

module-batch/src/main/java/inspiration/application/member/count/MemberCountJobConfig.java
module-batch/src/main/java/inspiration/application/slack/SlackService.java
module-batch/src/main/java/inspiration/application/slack/SlackServiceImpl.java
module-batch/src/main/java/inspiration/application/tag/TagRankingConfig.java
module-batch/src/main/java/inspiration/application/tag/TagRankingTasklet.java
module-batch/src/main/resources/batch.yml
module-domain/src/main/java/inspiration/domain/date/BaseTimeEntity.java
module-domain/src/main/java/inspiration/domain/member/Member.java

- releated #188 
- 가입한 수 조회 및 알려주는 배치 추가
- 새로가입한 회원 수를 일별, 월별로 집계해서 슬랙메시지에 파일로 보내줌 
-
-

feat: 가입 회원 수 집계 배치 추가

---

module-api/src/main/java/inspiration/domain/emailauth/EmailAuthService.java
module-api/src/main/java/inspiration/domain/emailauth/SignUpEmailSendService.java
module-domain/src/main/java/inspiration/infrastructure/mail/MailProperties.java
module-domain/src/main/resources/application-dev.yml
module-domain/src/main/resources/application-local.yml
module-domain/src/main/resources/application-prod.yml
module-domain/src/test/resources/application.yml
module-web/src/test/java/inspiration/v1/auth/AuthControllerTest.java
module-web/src/test/resources/application.yml

-resolved  #203
- 이메일 주소 검증시 + 문자 허용
-
- https://w1654930161-m7u149664.slack.com/archives/C03K8GBBBFC/p1680744843416209

feat: 이메일 주소 검증시 + 문자 허용

---

module-api/src/main/java/inspiration/domain/emailauth/EmailAuthService.java
module-api/src/main/java/inspiration/domain/member/request/ExtraInfoRequest.java
module-api/src/main/java/inspiration/signup/SignupService.java
module-web/src/main/java/inspiration/v1/signup/SignUpController.java
module-web/src/test/java/inspiration/v1/signup/SignUpControllerTest.java

- #203 
- ExtraInfoRequest: email 추가
- SignUpContorller: updateExtraInfo에서 QueryString 제거
- SignUpControllerTest: + 문자 포함한 email 테스트 추가
- EmailAuthService: 비밀번호 초기화 시 + 포함된 이메일 허용
-
-

fix: 이메일 검증 시 + 문자 허용

---

module-domain/src/main/resources/application-dev.yml
module-domain/src/main/resources/application-local.yml

config: 개발환경 DB 접속정보 변경

---

module-api/src/main/java/inspiration/domain/member/request/SignUpRequest.java

닉네임 Size 제한 수정

---

.github/workflows/prod_deploy.yml
module-domain/src/main/resources/application-prod.yml

feat: modify bucket name

---

.github/workflows/prod_deploy.yml
module-domain/src/main/resources/application-prod.yml

- #214 
- AWS 서버 이관으로 인한 설정 변경
-
-

영감탱 서버 이관 설정 변경

---

.github/workflows/prod_deploy.yml
module-domain/src/main/resources/application-prod.yml

github action 값 수정

---

.github/CODEOWNERS
.gitignore
module-domain/src/main/resources/application-local.yml

chore: config setup

---

.github/workflows/prod_deploy.yml

chore: add docker push step
